// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAioe43OK33okJF_bMzUecyFbN4uPl8ZM',
    appId: '1:629415622037:web:19605d79dec86992b1329c',
    messagingSenderId: '629415622037',
    projectId: 'flutter-fire-12245',
    authDomain: 'flutter-fire-12245.firebaseapp.com',
    storageBucket: 'flutter-fire-12245.firebasestorage.app',
    measurementId: 'G-BH55X64NW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiFrBXZnbWp6r_61zSUXCiApGDlAnpDlA',
    appId: '1:629415622037:android:5948ee6809c2f7a4b1329c',
    messagingSenderId: '629415622037',
    projectId: 'flutter-fire-12245',
    storageBucket: 'flutter-fire-12245.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3LzRcdlWMEefQemwqbEfAqT7rsIb8oOk',
    appId: '1:629415622037:ios:871049e82c39145fb1329c',
    messagingSenderId: '629415622037',
    projectId: 'flutter-fire-12245',
    storageBucket: 'flutter-fire-12245.firebasestorage.app',
    iosClientId: '629415622037-pbbcf0pfcsvl21e9ge8314g5mlk4gqsh.apps.googleusercontent.com',
    iosBundleId: 'app.fire.flutter.test',
  );
}
